### PR TITLE
Using memcpy in c to directly replace line by line copying #20 

### PR DESCRIPTION
**Pull request by Kayuii**
Using memcpy in c to directly replace line by line copying

### CODE REVIEW

**Comment by knopp** [comment]
I don't quite see the point of this - `copy_from_slice` should already be doing `memcpy` in release build.

**Comment by Kayuii** [comment]
I have changed several Android models, and there has always been a situation where the buf. stride is greater than buf. width. Copying line by line is also a problem. If you don't use memcpy, how do you write copying line by line?

**Comment by knopp** [comment]
If stride > width (which might happen, the code right now is bit too lazy, this need to be addressed), then the buffer needs to be iterated line by line and each one needs to be copied separately.

**Comment by Kayuii** [comment]
I used the following code to copy line by line, but it seems to be unsuccessful. I don't know how to implement it, so I switched to copying using memcpy
```
for row in 0..buf.height {
    let src_offset = (row * buf.stride * 4) as usize;
    let dst_offset = (row * buf.width * 4) as usize;  
    let src_slice = &payload.data[src_offset..(src_offset + (buf.width * 4) as usize)];        
    let dst_slice = &mut data[dst_offset..(dst_offset + (buf.width * 4) as usize)];   
    dst_slice.copy_from_slice(src_slice);
}
```

**Comment by knopp** [comment]
For reference, this PR should fix the stride issue: https://github.com/irondash/irondash/pull/27

**Pull request closed without merging**
